# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - run: npm install
#     - run: npm run test
    
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-test
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Deploy to Production branch
#       uses: JamesIves/github-pages-deploy-action@4.1.8
#       with:
#         branch: production
#         folder: .
